AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Max: 120
